Clean up LocUtils, update travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,68 +1,47 @@
+# NB: don't set `language: haskell` here
 
-# language: haskell
-# before_install:
-#     - "cabal update"
-#     - "cabal install hspec"
-#     - "cabal install happy"
-
-
-
-# See http://www.reddit.com/r/haskell/comments/1os3f6/how_to_use_travisci_with_multiple_ghc_versions/
-
+# See also https://github.com/hvr/multi-ghc-travis for more information
 env:
- # - GHCVER=6.12.3
- # - GHCVER=7.0.1
- # - GHCVER=7.0.2
- # - GHCVER=7.0.3
- # - GHCVER=7.0.4
- # - GHCVER=7.2.1
- # - GHCVER=7.2.2
-# - GHCVER=7.4.1
- - GHCVER=7.4.2
-# - GHCVER=7.6.1
-# - GHCVER=7.6.2
- - GHCVER=7.6.3
- - GHCVER=7.8.2
-# - GHCVER=head
+ - CABALVER=head GHCVER=head   # see section about GHC HEAD snapshots
 
-matrix:
-  allow_failures:
-   - env: GHCVER=7.8.2
+# matrix:
+#   allow_failures:
+#    - env: GHCVER=head  CABALVER=1.20
 
+# Note: the distinction between `before_install` and `install` is not important.
 before_install:
- - sudo add-apt-repository -y ppa:hvr/ghc
- - sudo apt-get update
- - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
- - export PATH=/opt/ghc/$GHCVER/bin:$PATH
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 
 install:
- - cabal-1.18 update
- # - cabal-1.18 install QuickCheck-2.6 # hspec is broken against 2.7
- - cabal-1.18 install happy
- - cabal-1.18 install alex
- # - cabal-1.18 install haddock
- # - cabal-1.18 install haddock-2.13.2.1
- # - cabal-1.18 install haddock-2.11.1
- # - cabal-1.18 install hspec-discover # For one of the tests
- - if [ "$GHCVER" = "6.12.3" ]; then
-      cabal-1.18 install --only-dependencies;
-      cabal-1.18 install 'QuickCheck==2.6.*';
-   else
-      cabal-1.18 install --only-dependencies --enable-tests;
-   fi
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - travis_retry cabal update
+ - cabal install alex happy
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks
 
+# Here starts the actual work to be performed for the package under
+# test; any command which exits with a non-zero exit code causes the
+# build to fail.
 script:
- # - cd tests/ && runghc ./GenTests.hs && cd ..
- - cabal-1.18 configure --enable-tests
- - cabal-1.18 build
- - cabal-1.18 test
- - cabal-1.18 check
- - if [ "$GHCVER" = "7.4.2" ]; then
-      echo "skipping";
-   else
-      cabal-1.18 haddock;
-   fi
- - cabal-1.18 sdist
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+ - cabal build   # this builds all libraries and executables (including tests/benchmarks)
+ - cabal test
+ - cabal check
+ - cabal sdist   # tests that a source-distribution can be generated
+
+# The following scriptlet checks that the resulting source distribution can be built & installed
+ # - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+ #   cd dist/;
+ #   if [ -f "$SRC_TGZ" ]; then
+ #      cabal install --force-reinstalls "$SRC_TGZ";
+ #   else
+ #      echo "expected '$SRC_TGZ' not found";
+ #      exit 1;
+
 
 notifications:
   irc: "irc.freenode.org#haskell-refactorer"
